version: '3.8'

services:
  frontend:
    build:
      context: ./solana-explorer-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - BACKEND_API_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./solana-explorer-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

networks:
  default:
    driver: bridge
